export const colorThemes = {
  forest: {
    name: "Forest",
    colors: {
      primary: "#2f7f5f",
      primaryHover: "#d14d41",
      secondary: "#95b89c",
      secondaryHover: "#e76f51",
      background: "#f7f9f3",
      neutral:"#F5F0E8",
      backgroundGradientStart: "#f7f9f3",
      backgroundGradientEnd: "#e7efe1",
      cardBackground: "#ffffff",
      textPrimary: "#234d2b",
      textSecondary: "#2c3e2f",
      tooltipBg: "rgba(18, 43, 25, 0.92)",
      tooltipText: "#f2f9f3",
      stroke: "#ffffff",
      
      panelShadow: "rgba(46, 73, 38, 0.1)",
    },
  },
//   ocean: {
//     name: "Ocean",
//     colors: {
//       primary: "#0077be",
//       primaryHover: "#ff6b6b",
//       secondary: "#4a9eff",
//       secondaryHover: "#ff8787",
//       background: "#e8f4f8",
//       backgroundGradientStart: "#e8f4f8",
//       backgroundGradientEnd: "#c8e6f5",
//       cardBackground: "#ffffff",
//       textPrimary: "#004a7a",
//       textSecondary: "#1a3a5a",
//       tooltipBg: "rgba(0, 77, 190, 0.92)",
//       tooltipText: "#e8f4f8",
//       stroke: "#ffffff",
//       panelShadow: "rgba(0, 77, 190, 0.1)",
//     },
//   },
//   sunset: {
//     name: "Sunset",
//     colors: {
//       primary: "#d14d41",
//       primaryHover: "#ff6b6b",
//       secondary: "#f08080",
//       secondaryHover: "#ffa500",
//       background: "#ffe8d6",
//       backgroundGradientStart: "#ffe8d6",
//       backgroundGradientEnd: "#ffd4a3",
//       cardBackground: "#ffffff",
//       textPrimary: "#8b4513",
//       textSecondary: "#a0522d",
//       tooltipBg: "rgba(209, 77, 65, 0.92)",
//       tooltipText: "#ffe8d6",
//       stroke: "#ffffff",
//       panelShadow: "rgba(209, 77, 65, 0.1)",
//     },
//   },
//   midnight: {
//     name: "Midnight",
//     colors: {
//       primary: "#1a1a2e",
//       primaryHover: "#16c784",
//       secondary: "#0f3460",
//       secondaryHover: "#00d4ff",
//       background: "#0f1419",
//       backgroundGradientStart: "#0f1419",
//       backgroundGradientEnd: "#1a1f2e",
//       cardBackground: "#16213e",
//       textPrimary: "#e0e0e0",
//       textSecondary: "#b0b0b0",
//       tooltipBg: "rgba(26, 26, 46, 0.95)",
//       tooltipText: "#e0e0e0",
//       stroke: "#2a3a4a",
//       panelShadow: "rgba(0, 0, 0, 0.3)",
//     },
//   },
//   desert: {
//     name: "Desert",
//     colors: {
//       primary: "#cd853f",
//       primaryHover: "#ff8c00",
//       secondary: "#daa520",
//       secondaryHover: "#ffa500",
//       background: "#f5deb3",
//       backgroundGradientStart: "#f5deb3",
//       backgroundGradientEnd: "#ffe4b5",
//       cardBackground: "#fffaf0",
//       textPrimary: "#654321",
//       textSecondary: "#8b6914",
//       tooltipBg: "rgba(205, 133, 63, 0.92)",
//       tooltipText: "#fffaf0",
//       stroke: "#ffffff",
//       panelShadow: "rgba(205, 133, 63, 0.1)",
//     },
//   },
//   emerald: {
//     name: "Emerald",
//     colors: {
//       primary: "#27ae60",
//       primaryHover: "#e74c3c",
//       secondary: "#2ecc71",
//       secondaryHover: "#e67e22",
//       background: "#ecf0f1",
//       backgroundGradientStart: "#ecf0f1",
//       backgroundGradientEnd: "#d5dbdb",
//       cardBackground: "#ffffff",
//       textPrimary: "#16a085",
//       textSecondary: "#27ae60",
//       tooltipBg: "rgba(39, 174, 96, 0.92)",
//       tooltipText: "#ecf0f1",
//       stroke: "#ffffff",
//       panelShadow: "rgba(39, 174, 96, 0.1)",
//     },
//   },
};

export const getTheme = (themeName) => {
  return colorThemes[themeName] || colorThemes.forest;
};

export const getThemeNames = () => {
  return Object.keys(colorThemes);
};
